apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul-server
  template:
    metadata:
      labels:
        app: consul-server
    spec:
      containers:
        - name: consul-server
          image: consul
          ports:
            - containerPort: 8500
          imagePullPolicy: Always
          env:
            - name: CONSUL_BIND_INTERFACE
              value: "eth0"
---
apiVersion: v1
kind: Service
metadata:
  name: consul-server-svc
spec:
  selector:
    app: consul-server
  ports:
    - port: 8500
      targetPort: 8500
      nodePort: 32500
  type: NodePort